# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-16 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cardetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pingpai', models.CharField(max_length=50)),
                ('chexi', models.CharField(max_length=50)),
                ('chexin', models.CharField(max_length=50)),
                ('licheng', models.CharField(max_length=50)),
                ('pailiang', models.CharField(max_length=50)),
                ('biansuxiang', models.CharField(max_length=50)),
                ('spsj', models.CharField(max_length=50)),
                ('spd', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('zws', models.CharField(max_length=50)),
                ('rylx', models.CharField(max_length=50)),
                ('chezhu', models.CharField(max_length=50)),
                ('lie1', models.CharField(max_length=50)),
                ('lie2', models.CharField(max_length=50)),
                ('lie3', models.CharField(max_length=50)),
                ('lie4', models.CharField(max_length=50)),
                ('lie5', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('lie1', models.CharField(max_length=50)),
                ('lie2', models.CharField(max_length=50)),
                ('lie3', models.CharField(max_length=50)),
                ('lie4', models.CharField(max_length=50)),
                ('lie5', models.CharField(max_length=50)),
            ],
        ),
    ]
