# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buycaruser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyertel', models.CharField(max_length=20)),
            ],
            managers=[
                ('btel', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='admin',
            managers=[
                ('adm', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cardetail',
            managers=[
                ('car', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('usu', django.db.models.manager.Manager()),
            ],
        ),
    ]
